version: 2
updates:
  - package-ecosystem: cargo # zizmor: ignore[dependabot-cooldown] # Unless dependencies are pinned/locked, the effect is limited.
    directories:
      - /
      # crates with [workspace] table are not recognized by the above 'directory: /'
      - /tests/asm-test
      - /tests/avr
      - /tests/gba
      - /tests/msp430
      - /tests/no-std-qemu
      - /tests/xtensa
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # For test on old rustc.
      - dependency-name: libc
    labels: []
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    commit-message:
      prefix: ''
    labels: []
